language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

service:
  - postgresql

before_install:
  - export APP_SETTINGS="project.server.config.TestingConfig"
  - export SECRET_KEY="justatest"
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database flask_jwt_auth_test;' -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

script:
  - python manage.py cov

after_success:
  coveralls
